Load Fonts from assets.sparkbox.com
sparkbox/designsystemssurvey pull request #332
Opened 2022-05-03 15:30 UTC by zastrow

This work updates the 2020 and 2021 pages to load fonts from assets.sparkbox.com instead of locally-hosted.

After this is tested, working, and merged we will scrub the repo of the necessary locally-hosted fonts.

2022-05-03 15:54 UTC, reedspool commented
Code looks fine - but it's all URLs so it requires detailed verification that those URLs are correct.

2022-05-06 18:49 UTC, mlogsdon18 requested changes
Found a couple of typos in the URLs here when I double-checked them.

2022-05-06 18:49 UTC, mlogsdon18 commented on src/scss/2020/generic/_fonts.scss
> +       url('https://assets.sparkbox.com/fonts/solesole-serif-headline-extrabold/font.woff') format('woff');
Same typo here! Missing a slash. "/fonts/solesole-serif-headline-extrabold/" should be "/fonts/sole/sole-serif-headline-extrabold/"

2022-05-06 18:49 UTC, mlogsdon18 commented on src/scss/2020/generic/_fonts.scss
> +       url('https://assets.sparkbox.com/fonts/solesole-serif-text-light/font.woff') format('woff');
Same typo as above here. Need the slash after the first "sole"

2022-05-06 18:49 UTC, mlogsdon18 commented on src/pages/2020.js
> +          <link rel="preload" as="font" href="https://assets.sparkbox.com/fonts/solesole-serif-text-light/font.woff2" type="font/woff2" crossorigin="anonymous" />
Both line 31 and 32 have a typo. They need a / after the first "sole". For example, "https://assets.sparkbox.com/fonts/solesole-serif-headline-extrabold/font.woff2" should be "https://assets.sparkbox.com/fonts/sole/sole-serif-headline-extrabold/font.woff2"

2022-05-08 21:07 UTC, zastrow commented
@mlogsdon18 All the facepalms. Thank you!!! I’ve fixed those and pushed back up. Also, the assets URLs are working now if you want to see the deploy. It’s exciting!

2022-05-09 13:19 UTC, mlogsdon18 approved these changes
These look good now!

2022-05-09 15:16 UTC, merged